_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  webform_clientside_validation: -1
  auto_entitylabel: -100
  action: 0
  action_example: 0
  add_content_by_bundle: 0
  add_content_modal: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  ajax_example: 0
  allowed_formats: 0
  asset_injector: 0
  automated_cron: 0
  backup_migrate: 0
  basic_auth: 0
  batch_example: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_example: 0
  block_field: 0
  bpmn_io: 0
  breakpoint: 0
  cache_example: 0
  captcha: 0
  ckeditor5: 0
  clientside_validation: 0
  clientside_validation_demo: 0
  clientside_validation_jquery: 0
  comment: 0
  config: 0
  config_entity_example: 0
  config_ignore: 0
  contact: 0
  content_entity_example: 0
  content_moderation: 0
  contextual: 0
  cron_example: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  dblog: 0
  dbtng_example: 0
  devel: 0
  devel_generate: 0
  devel_kint_extras: 0
  download_statistics: 0
  ds_devel: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  eca: 0
  eca_access: 0
  eca_base: 0
  eca_misc: 0
  eca_modeller_bpmn: 0
  eca_ui: 0
  eca_user: 0
  editor: 0
  email_example: 0
  enhanced_button_link: 0
  entity: 0
  entity_events: 0
  entity_print: 0
  entity_print_views: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  events_example: 0
  examples: 0
  field: 0
  field_example: 0
  field_layout: 0
  field_permission_example: 0
  field_ui: 0
  file: 0
  file_download_link: 0
  file_download_link_media: 0
  file_example: 0
  filter: 0
  force_password_change: 0
  form_api_example: 0
  fullcalendar_view: 0
  gatsby_extras: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  js_example: 0
  jsonapi: 0
  jsonapi_defaults: 0
  jsonapi_extras: 0
  layout_builder: 0
  layout_builder_expose_all_field_blocks: 0
  layout_discovery: 0
  layout_paragraphs: 0
  link: 0
  mailchimp: 0
  mailchimp_campaign: 0
  mailchimp_events: 0
  mailchimp_events_example: 0
  mailchimp_lists: 0
  mailchimp_signup: 0
  mailchimp_webform_handler: 0
  mailer_transport: 0
  media: 0
  media_library: 0
  menu_example: 0
  menu_link_attributes: 0
  menu_link_content: 0
  menu_ui: 0
  message_banner: 0
  migrate: 0
  migrate_json_example: 0
  migrate_plus: 0
  migrate_tools: 0
  multiple_registration: 0
  mysql: 0
  nbw_data_app: 0
  nbw_tools: 0
  nbw_users_registration: 0
  node: 0
  node_type_example: 0
  options: 0
  page_cache: 0
  page_example: 0
  pager_example: 0
  path: 0
  path_alias: 0
  phpass: 0
  phpunit_example: 0
  plugin_type_example: 0
  profile: 0
  queue_example: 0
  render_example: 0
  responsive_image: 0
  rest: 0
  scheduler: 0
  search: 0
  search_api: 0
  search_api_opensearch: 0
  serialization: 0
  session_example: 0
  shield: 0
  shortcut: 0
  smart_date: 0
  smart_date_calendar_kit: 0
  smart_date_recur: 0
  smart_date_starter_kit: 0
  statistics: 0
  stream_wrapper_example: 0
  symfony_mailer: 0
  symfony_mailer_log: 0
  symfony_mailer_queue: 0
  syslog: 0
  system: 0
  tabledrag_example: 0
  tablesort_example: 0
  taxonomy: 0
  telephone: 0
  testing_example: 0
  text: 0
  theming_example: 0
  token: 0
  toolbar: 0
  tour: 0
  tour_example: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  verf: 0
  viewfield: 0
  views_add_button: 0
  views_autocomplete_filters: 0
  views_bootstrap: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_access: 0
  webform_attachment: 0
  webform_cards: 0
  webform_content_creator: 0
  webform_demo_application_evaluation: 0
  webform_demo_event_registration: 0
  webform_demo_region_contact: 0
  webform_devel: 0
  webform_entity_print: 0
  webform_entity_print_attachment: 0
  webform_example_composite: 0
  webform_example_custom_form: 0
  webform_example_element: 0
  webform_example_element_properties: 0
  webform_examples: 0
  webform_image_select: 0
  webform_jqueryui_datepicker: 0
  webform_mailchimp: 0
  webform_node: 0
  webform_options_custom: 0
  webform_options_limit: 0
  webform_scheduled_email: 0
  webform_share: 0
  webform_submission_log: 0
  webform_templates: 0
  webform_ui: 0
  webform_user_registration: 0
  workflows: 0
  ds: 1
  eca_form: 1
  pathauto: 1
  ds_extras: 2
  views: 10
  paragraphs: 11
  gatsby: 100
  standard: 1000
theme:
  olivero: 0
  claro: 0
  stable: 0
  classy: 0
  uswds_base: 0
  nbw_uswds: 0
  nbw_custom_theme: 0
profile: standard
