name: 'Environment Indicator'
type: module
description: 'Adds a color indicator for the different environments.'
package: Development
core_version_requirement: '^9.3 || ^10 || ^11'
configure: environment_indicator.settings

# Information added by Drupal.org packaging script on 2025-07-23
version: '4.0.25'
project: 'environment_indicator'
datestamp: 1753296296
